#!/bin/bash

export FLASK_APP=app.py
export FLASK_ENV=development

service mysql start

sudo python3 -m flask run --host=0.0.0.0 --port=5000 &

sudo mysql -u root -p

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';
FLUSH PRIVILEGES;
EXIT;

CREATE DATABASE lms
USE lms

-----------------
minikube start --driver=docker
-------------------

docker build -t splunk-python-app:latest .
docker run -p 5000:5000 splunk-python-app:latest

------------------

kubectl apply -f mysql.yaml
kubectl apply -f flask.yaml

kubectl port-forward svc/flask-service -n demo-app 8080:80



