#!/bin/bash

export FLASK_APP=app.py
export FLASK_ENV=development

service mysql start

sudo python3 -m flask run --host=0.0.0.0 --port=5000 &

sudo mysql -u root -p

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';
FLUSH PRIVILEGES;
EXIT;

CREATE DATABASE lms;
USE lms;

-------------------

docker build -t splunk-python-app:latest .
docker run -p 5000:5000 splunk-python-app:latest

docker tag splunk-python-app:latest jacksonlobo/splunk-python-app:latest
docker push jacksonlobo/splunk-python-app:latest

------------------

kubectl apply -f mysql.yaml
kubectl apply -f flask.yaml

kubectl port-forward service/splunk-python-app-service 8080:80

-----------------------

INSERT INTO `users` (`id`, `name`, `email`, `password`, `bio`, `mob`, `lock`, `created_at`) VALUES
(7, 'Jack', 'jack@gmail.com', 'jack', 'Hi :)! Long time no see ❤️', '', 0, '2025-03-04 23:07:53');


INSERT INTO `users` (`id`, `name`, `email`, `password`, `bio`, `mob`, `lock`, `created_at`) VALUES
(8, 'ABC', 'abc@gmail.com', 'abc', 'Hello :)! Long time no see ❤️', '', 0, '2025-03-03 23:07:53');

INSERT INTO `admin` (`id`, `email`, `password`) VALUES
(2, 'admin@gmail.com', 'admin');

