#!/bin/bash

export FLASK_APP=app.py
export FLASK_ENV=development

service mysql start

python3 -m flask run --host=0.0.0.0 --port=5000

sudo mysql -u root -p

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';
FLUSH PRIVILEGES;
EXIT;

CREATE DATABASE lms
USE lms
