apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-python-app
  labels:
    app: splunk-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: splunk-python-app
  template:
    metadata:
      labels:
        app: splunk-python-app
    spec:
      containers:
      - name: splunk-python-app
        image: jacksonlobo/splunk-python-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "app.py"
        - name: FLASK_ENV
          value: "production"
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: ""
        - name: MYSQL_DB
          value: "lms"


---

apiVersion: v1
kind: Service
metadata:
  name: splunk-python-app-service
spec:
  selector:
    app: splunk-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer